---
title: "lab0"
date: "8/30/2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tibble)
library(ggplot2)
library(fiftystater)
```

## 1. Visualizing the data

### 1.1 Plot Murder vs Assault

```{r data, include=FALSE}
setwd("/Users/Hongxu/Dropbox/Code/STAT_215A_git/Lab\ 0")
data("USArrests")
statecoord = read.table("stateCoord.txt")
statecoord = rownames_to_column(statecoord)
USArrests = rownames_to_column(USArrests)

statecoord$rowname <- sub("-", " ", statecoord$rowname)
Combine <- full_join(USArrests,statecoord,by = "rowname", copy = TRUE)
```


```{r 1.1, echo=FALSE}
p <- ggplot(Combine, aes(Murder, Assault))
p + geom_point()
```

### 1.2 Rape with urban population

```{r 1.2, echo=FALSE}
OutlierRatio <- Combine[5] / Combine[4]
OutlierMean <- mean(OutlierRatio$Rape, na.rm = TRUE)
OutlierSD <- sqrt(var(OutlierRatio))[1,1]
Outlier <- OutlierRatio > OutlierMean + 3 * OutlierSD
colnames(Outlier) <- c("RapeOutlier")
Combine <- cbind(Combine, Outlier)
p3 <- ggplot(Combine, aes(UrbanPop, Rape))
p3 + geom_point(col = ifelse(Combine["RapeOutlier"] == TRUE, 'red','black'))
```

### 1.3 Plots with the state names

```{r 1.3, echo=FALSE}
p4 <- ggplot(Combine, aes(UrbanPop, Rape, label = rowname))
p4 + geom_text()
```

### 1.4 Plot a map

```{r 1.4, echo=FALSE}
data("fifty_states") 
data("USArrests")
crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
p5 <- ggplot(crimes, aes(map_id = state)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = Murder), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())

p5 + fifty_states_inset_boxes() 
```

## 2.Regression
### 2.1 Fit a linear regression of urban population on Rape
### 2.2 Plot predicted values vs the residuals
```{r 2.1 2.2, echo=FALSE}
# fit a linear regression of UrbanPop on Rape
fit1 <- lm(UrbanPop ~ Rape, data=Combine)

#plot predicted values vs residuals
FitNum <- cbind(fitted(fit1), residuals(fit1))
colnames(FitNum) <- c("predict","residuals")
Combine <- cbind(Combine, FitNum)
p6 <- ggplot(Combine, aes(predict,residuals))
p6 +geom_point()
```

### 2.3 Rape vs urban population with regression

```{r 2.3, echo=FALSE}
p7 <- ggplot(Combine, aes(UrbanPop, Rape))+
  geom_smooth(method = "lm", se=FALSE, color="blue", formula = y ~ x,show.legend = TRUE) +
  geom_point(color = "blue")
p7
```

### 2.4 refit without outlier

```{r 2.4, echo=FALSE}
Combine2 <- filter(Combine, RapeOutlier == FALSE)
p8 <- p7 + geom_smooth(aes(UrbanPop,Rape), data = Combine2, method = "lm", se=FALSE, color="red", formula = y ~ x, show.legend = TRUE)
```

### 2.6 Publishable graph
```{r 2.5, echo=FALSE}
p8 <- p8 + ggtitle("Linear Regression of UrbanPop on Rape")
p8 +  scale_color_manual(name="Regression Lines")
```

